name: ng2_g_signin_site
description: A example site of ng2_g_signin.
version: 0.3.2
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  angular: ^5.1.0
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4
  ng2_g_signin:
    path: ../../../ng2_g_signin

